const cocktails = [
     {
      "alcoholPreferences": "Gin",
      "Name": "gin1",
      "Cocktail Name": "French75",
      "Description": "A sophisticated, sparkling cocktail with a refreshing citrus twist.",
      "Ingredients": "1 oz gin\n1\/2 oz fresh lemon juice\n1\/2 oz simple syrup\n3 oz Champagne or sparkling wine\nLemon twist (for garnish)",
      "Recipe": "1. In a cocktail shaker, combine gin, lemon juice, and simple syrup with ice.\n2. Shake well and strain into a chilled \n3. Champagne flute.\nTop with Champagne and garnish with a lemon twist.",
      "caloriePreference": "Low",
      "Kcal": 120,
      "flavorProfile": "Sour, Floral",
      "Location": "\/assets\/alcoholImages\/gin\/gin1.png"
     },
     {
      "alcoholPreferences": "Gin",
      "Name": "gin2",
      "Cocktail Name": "Pink Moon",
      "Description": "A vibrant, fruity cocktail with a delightful balance of floral and berry notes.",
      "Ingredients": "1 1\/2 oz gin\n1\/2 oz elderflower liqueur\n1 oz fresh grapefruit juice\n1\/4 oz simple syrup\nSplash of cranberry juice\nGrapefruit slice (for garnish)",
      "Recipe": "1. In a shaker, add gin, elderflower liqueur, grapefruit juice, simple syrup, and ice.\n2. Shake and strain into a chilled coupe glass.\n3. Add a splash of cranberry juice for color and garnish with a grapefruit slice.",
      "caloriePreference": "Low",
      "Kcal": 140,
      "flavorProfile": "Fruity, Floral",
      "Location": "\/assets\/alcoholImages\/gin\/gin2.png"
     },
     {
      "alcoholPreferences": "Gin",
      "Name": "gin3",
      "Cocktail Name": "Gin & Tonic",
      "Description": "A classic and refreshing cocktail with a perfect blend of gin and tonic water.",
      "Ingredients": "2 oz gin\n4 oz tonic water\nLime wedge (for garnish)",
      "Recipe": "1. Fill a glass with ice cubes, pour in gin, and top with tonic water.\n2. Stir gently and garnish with a lime wedge.",
      "caloriePreference": "Low",
      "Kcal": 120,
      "flavorProfile": "Bitter, Herbal",
      "Location": "\/assets\/alcoholImages\/gin\/gin3.png"
     },
     {
      "alcoholPreferences": "Gin",
      "Name": "gin4",
      "Cocktail Name": "Gin Lemon",
      "Description": "A zesty and refreshing gin cocktail with a bold citrus flavor.",
      "Ingredients": "1 1\/2 oz gin\n1 oz fresh lemon juice\n1\/2 oz simple syrup\nLemon wheel (for garnish)",
      "Recipe": "1. In a shaker, add gin, lemon juice, and simple syrup with ice.\n2. Shake well and strain into an ice-filled rocks glass.\n3. Garnish with a lemon wheel.",
      "caloriePreference": "Low",
      "Kcal": 110,
      "flavorProfile": "Sour",
      "Location": "\/assets\/alcoholImages\/gin\/gin4.png"
     },
     {
      "alcoholPreferences": "Gin",
      "Name": "gin5",
      "Cocktail Name": "Turf Cocktail",
      "Description": "A classic gin martini with a hint of herbal complexity.",
      "Ingredients": "1 1\/2 oz gin\n1\/2 oz dry vermouth\n1\/4 oz absinthe or pastis (optional)\n2 dashes orange bitters\nLemon twist or olive (for garnish)",
      "Recipe": "1. Stir gin, dry vermouth, absinthe (if using), and bitters with ice in a mixing glass.\n2. Strain into a chilled martini glass.\n3. Garnish with a lemon twist or olive.",
      "caloriePreference": "Medium",
      "Kcal": 150,
      "flavorProfile": "Herbal, Bitter",
      "Location": "\/assets\/alcoholImages\/gin\/gin5.png"
     },
     {
      "alcoholPreferences": "Gin",
      "Name": "gin6",
      "Cocktail Name": "Mountain Bramble",
      "Description": "A refreshing cocktail with berry flavors and a hint of citrus.",
      "Ingredients": "1 1\/2 oz gin\n1\/2 oz crème de mûre (blackberry liqueur)\n1\/2 oz fresh lemon juice\n1\/4 oz simple syrup\nFresh blackberries (for garnish)",
      "Recipe": "1. In a shaker, combine gin, lemon juice, and simple syrup with ice.\n2. Shake and strain into a glass filled with crushed ice.\n3. Drizzle crème de mûre over the top and garnish with blackberries.",
      "caloriePreference": "Medium",
      "Kcal": 160,
      "flavorProfile": "Fruity, Sour",
      "Location": "\/assets\/alcoholImages\/gin\/gin6.png"
     },
     {
      "alcoholPreferences": "Gin",
      "Name": "gin7",
      "Cocktail Name": "Martini",
      "Description": "A classic gin martini that’s dry and sophisticated.",
      "Ingredients": "2 oz gin\n1\/2 oz dry vermouth\nLemon twist or olive (for garnish)",
      "Recipe": "1. Stir gin and dry vermouth with ice in a mixing glass.\n2. Strain into a chilled martini glass.\n3. Garnish with a lemon twist or olive.",
      "caloriePreference": "Medium",
      "Kcal": 200,
      "flavorProfile": "Herbal, Bitter",
      "Location": "\/assets\/alcoholImages\/gin\/gin7.png"
     },
     {
      "alcoholPreferences": "Gin",
      "Name": "gin8",
      "Cocktail Name": "Ramos Ginn Fizz",
      "Description": "A creamy, citrusy gin cocktail with a silky texture and a touch of sweetness.",
      "Ingredients": "2 oz gin\n1\/2 oz fresh lemon juice\n1\/2 oz fresh lime juice\n1 oz simple syrup\n1 oz heavy cream\n1 egg white\n2-3 drops orange flower water\nClub soda (to top)",
      "Recipe": "1. In a shaker, combine gin, lemon juice, lime juice, simple syrup, cream, egg white, and orange flower water.\n2. Shake vigorously without ice for 15-20 seconds, then add ice and shake again.\n3. Strain into a chilled highball glass and top with club soda for a frothy finish.",
      "caloriePreference": "Indulgent",
      "Kcal": 230,
      "flavorProfile": "Sour, Sweet",
      "Location": "\/assets\/alcoholImages\/gin\/gin8.png"
     },
     {
      "alcoholPreferences": "Rum",
      "Name": "rum1",
      "Cocktail Name": "Barracuda",
      "Description": "A tropical, sparkling cocktail with a sweet and fruity blend of pineapple and rum.",
      "Ingredients": "1 1\/2 oz gold rum\n1\/2 oz Galliano liqueur\n2 oz fresh pineapple juice\nDash of lime juice\nProsecco or Champagne (to top)",
      "Recipe": "1. Shake rum, Galliano, pineapple juice, and lime juice with ice.\n2. Strain into a chilled glass and top with Prosecco.",
      "caloriePreference": "Medium",
      "Kcal": 170,
      "flavorProfile": "Fruity, Sweet",
      "Location": "\/assets\/alcoholImages\/rum\/rum1.png"
     },
     {
      "alcoholPreferences": "Rum",
      "Name": "rum2",
      "Cocktail Name": "Chocolate Rum Cocktail",
      "Description": "A rich and creamy cocktail with a chocolatey twist, perfect for dessert lovers.",
      "Ingredients": "1 1\/2 oz dark rum\n1 oz crème de cacao\n1 oz cream or half-and-half\nChocolate shavings (for garnish)",
      "Recipe": "1. Shake rum, crème de cacao, and cream with ice.\n2. Strain into a chilled glass and garnish with chocolate shavings.",
      "caloriePreference": "Indulgent",
      "Kcal": 250,
      "flavorProfile": "Sweet, Nutty",
      "Location": "\/assets\/alcoholImages\/rum\/rum2.png"
     },
     {
      "alcoholPreferences": "Rum",
      "Name": "rum3",
      "Cocktail Name": "Captain Kidd's Punch",
      "Description": "A vibrant, tropical punch with a mix of rum, fruit, and spices.",
      "Ingredients": "1 oz dark rum\n1 oz light rum\n1 oz pineapple juice\n1 oz orange juice\nDash of grenadine\nDash of bitters\nOrange slice and cherry (for garnish)",
      "Recipe": "1. Combine both rums, juices, grenadine, and bitters with ice in a shaker.\n2. Shake well and strain into an ice-filled glass.\nGarnish with an orange slice and cherry.",
      "caloriePreference": "Medium",
      "Kcal": 200,
      "flavorProfile": "Fruity, Spicy",
      "Location": "\/assets\/alcoholImages\/rum\/rum3.png"
     },
     {
      "alcoholPreferences": "Rum",
      "Name": "rum4",
      "Cocktail Name": "Funk and Soul",
      "Description": "A bold, smoky cocktail with a hint of spice, perfect for adventurous palates.",
      "Ingredients": "1 1\/2 oz mezcal\n1\/2 oz triple sec\n1 oz fresh lime juice\n1\/2 oz simple syrup\nChili pepper (for garnish)",
      "Recipe": "1. Shake mezcal, triple sec, lime juice, and simple syrup with ice.\n2. Strain into a chilled glass and garnish with a chili pepper.",
      "caloriePreference": "Low",
      "Kcal": 140,
      "flavorProfile": "Smoky, Spicy",
      "Location": "\/assets\/alcoholImages\/rum\/rum4.png"
     },
     {
      "alcoholPreferences": "Rum",
      "Name": "rum5",
      "Cocktail Name": "Pure Passion",
      "Description": "A tropical cocktail that combines rum with the exotic flavors of passionfruit and coconut.",
      "Ingredients": "1 1\/2 oz white rum\n1 oz passionfruit juice\n1 oz coconut cream\n1\/2 oz lime juice\nPassionfruit slice (for garnish)",
      "Recipe": "1. Shake rum, passionfruit juice, coconut cream, and lime juice with ice.\n2. Strain into a chilled glass and garnish with a passionfruit slice.",
      "caloriePreference": "Medium",
      "Kcal": 180,
      "flavorProfile": "Fruity, Sweet",
      "Location": "\/assets\/alcoholImages\/rum\/rum5.png"
     },
     {
      "alcoholPreferences": "Rum",
      "Name": "rum6",
      "Cocktail Name": "Rum Punch",
      "Description": "A classic tropical cocktail bursting with a blend of fruit juices and rum.",
      "Ingredients": "1 oz light rum\n1 oz dark rum\n2 oz orange juice\n2 oz pineapple juice\n1\/4 oz grenadine\nOrange slice and cherry (for garnish)",
      "Recipe": "1. Shake both rums, juices, and grenadine with ice.\n2. Strain into an ice-filled glass and garnish with an orange slice and cherry.",
      "caloriePreference": "Medium",
      "Kcal": 200,
      "flavorProfile": "Fruity, Sweet",
      "Location": "\/assets\/alcoholImages\/rum\/rum6.png"
     },
     {
      "alcoholPreferences": "Rum",
      "Name": "rum7",
      "Cocktail Name": "Zippy's Revenge",
      "Description": "A zesty, citrus-forward cocktail with a hint of herbal complexity.",
      "Ingredients": "1 1\/2 oz rum\n1\/2 oz Aperol\n1 oz fresh grapefruit juice\n1\/4 oz simple syrup\nGrapefruit twist (for garnish)",
      "Recipe": "1. Shake rum, Aperol, grapefruit juice, and simple syrup with ice.\n2. Strain into a chilled glass and garnish with a grapefruit twist.",
      "caloriePreference": "Medium",
      "Kcal": 150,
      "flavorProfile": "Bitter, Sour",
      "Location": "\/assets\/alcoholImages\/rum\/rum7.png"
     },
     {
      "alcoholPreferences": "Rum",
      "Name": "rum8",
      "Cocktail Name": "Zombie",
      "Description": "A strong, multi-layered tiki cocktail that combines various rums with tropical juices and spices.",
      "Ingredients": "1 oz white rum\n1 oz dark rum\n1 oz overproof rum\n1 oz pineapple juice\n1 oz lime juice\n1\/2 oz grenadine\n1\/4 oz falernum or allspice dram\nMint sprig (for garnish)",
      "Recipe": "1. Shake all ingredients (except overproof rum) with ice.\n2. Strain into a large glass filled with ice, and float the overproof rum on top.\n3. Garnish with a mint sprig.",
      "caloriePreference": "Indulgent",
      "Kcal": 260,
      "flavorProfile": "Fruity, Spicy",
      "Location": "\/assets\/alcoholImages\/rum\/rum8.png"
     },
     {
      "alcoholPreferences": "Tequila",
      "Name": "tequila1",
      "Cocktail Name": "Strawberry Margarita",
      "Description": "A fruity twist on the classic margarita, with sweet strawberries and a hint of lime.",
      "Ingredients": "1 1\/2 oz tequila\n1 oz triple sec\n1 oz fresh lime juice\n1\/2 cup fresh strawberries, hulled\nIce\nSalt or sugar for rimming (optional)\nStrawberry slice (for garnish)",
      "Recipe": "1. In a blender, combine tequila, triple sec, lime juice, strawberries, and ice. Blend until smooth.\n2. Rim the glass with salt or sugar if desired, then pour in the cocktail.\n3. Garnish with a strawberry slice.",
      "caloriePreference": "Medium",
      "Kcal": 180,
      "flavorProfile": "Fruity, Sour",
      "Location": "\/assets\/alcoholImages\/tequila\/tequila1.png"
     },
     {
      "alcoholPreferences": "Tequila",
      "Name": "tequila2",
      "Cocktail Name": "Tequila Sunrise",
      "Description": "A classic, layered cocktail with a vibrant mix of tequila, orange, and grenadine.",
      "Ingredients": "2 oz tequila\n4 oz orange juice\n1\/2 oz grenadine\nOrange slice and cherry (for garnish)",
      "Recipe": "1. Fill a glass with ice, pour in tequila and orange juice, and stir gently.\n2. Slowly pour grenadine over the back of a spoon to create a gradient.\n3. Garnish with an orange slice and cherry.",
      "caloriePreference": "Medium",
      "Kcal": 180,
      "flavorProfile": "Fruity, Sweet",
      "Location": "\/assets\/alcoholImages\/tequila\/tequila2.png"
     },
     {
      "alcoholPreferences": "Tequila",
      "Name": "tequila3",
      "Cocktail Name": "Paloma",
      "Description": "A refreshing, citrusy cocktail with tequila and grapefruit, perfect for hot days.",
      "Ingredients": "2 oz tequila\n1\/2 oz fresh lime juice\n4 oz grapefruit soda (or fresh grapefruit juice and club soda)\nSalt (optional, for rimming)\nLime wedge (for garnish)",
      "Recipe": "1. Rim the glass with salt if desired and add ice.\n2. Pour in tequila, lime juice, and top with grapefruit soda.\n3. Garnish with a lime wedge.",
      "caloriePreference": "Medium",
      "Kcal": 160,
      "flavorProfile": "Sour",
      "Location": "\/assets\/alcoholImages\/tequila\/tequila3.png"
     },
     {
      "alcoholPreferences": "Tequila",
      "Name": "tequila4",
      "Cocktail Name": "Winter Rita",
      "Description": "A seasonal margarita with a hint of cinnamon and winter citrus flavors.",
      "Ingredients": "1 1\/2 oz tequila\n1 oz orange liqueur\n1 oz fresh lime juice\n1 oz fresh orange juice\nDash of cinnamon\nCinnamon stick or orange slice (for garnish)",
      "Recipe": "1. In a shaker, combine tequila, orange liqueur, lime juice, orange juice, and a dash of cinnamon with ice.\n2. Shake and strain into a glass filled with ice.\n3. Garnish with a cinnamon stick or orange slice.",
      "caloriePreference": "Medium",
      "Kcal": 170,
      "flavorProfile": "Sour, Spicy",
      "Location": "\/assets\/alcoholImages\/tequila\/tequila4.png"
     },
     {
      "alcoholPreferences": "Tequila",
      "Name": "tequila5",
      "Cocktail Name": "Chipilo Cocktail",
      "Description": "A creamy cocktail with flavors of coffee, chocolate, and a hint of spice.",
      "Ingredients": "1 oz tequila\n1 oz coffee liqueur\n1 oz chocolate liqueur\n1 oz heavy cream\nGround cinnamon (for garnish)",
      "Recipe": "1. Shake tequila, coffee liqueur, chocolate liqueur, and cream with ice.\n2. Strain into a chilled glass and sprinkle with ground cinnamon.",
      "caloriePreference": "Indulgent",
      "Kcal": 250,
      "flavorProfile": "Nutty, Spicy",
      "Location": "\/assets\/alcoholImages\/tequila\/tequila5.png"
     },
     {
      "alcoholPreferences": "Tequila",
      "Name": "tequila6",
      "Cocktail Name": "Apple Grande",
      "Description": "A warm, spiced cocktail that blends tequila with apple cider for a cozy feel.",
      "Ingredients": "1 1\/2 oz tequila\n4 oz warm apple cider\n1\/4 oz maple syrup\nDash of cinnamon and nutmeg\nApple slice (for garnish)",
      "Recipe": "1. In a heat-proof glass, combine tequila, warm apple cider, maple syrup, and spices.\n2. Stir gently and garnish with an apple slice.",
      "caloriePreference": "Medium",
      "Kcal": 200,
      "flavorProfile": "Spicy, Fruity",
      "Location": "\/assets\/alcoholImages\/tequila\/tequila6.png"
     },
     {
      "alcoholPreferences": "Tequila",
      "Name": "tequila7",
      "Cocktail Name": "Montego Slay",
      "Description": "A tropical-inspired tequila cocktail with flavors of pineapple, coconut, and a hint of lime.",
      "Ingredients": "1 1\/2 oz tequila\n1 oz coconut cream\n2 oz pineapple juice\n1\/2 oz fresh lime juice\nPineapple slice or mint sprig (for garnish)",
      "Recipe": "1. Shake tequila, coconut cream, pineapple juice, and lime juice with ice.\n2. Strain into an ice-filled glass and garnish with a pineapple slice or mint sprig.",
      "caloriePreference": "Medium",
      "Kcal": 220,
      "flavorProfile": "Fruity, Sweet",
      "Location": "\/assets\/alcoholImages\/tequila\/tequila7.png"
     },
     {
      "alcoholPreferences": "Brandy",
      "Name": "brandy1",
      "Cocktail Name": "City Slicker",
      "Description": "A smooth, slightly tart brandy cocktail with a hint of lemon and cherry.",
      "Ingredients": "1 1\/2 oz brandy\n1\/2 oz triple sec\n1\/2 oz fresh lemon juice\nCherry (for garnish)",
      "Recipe": "1. Shake brandy, triple sec, and lemon juice with ice.\n2. Strain into a chilled glass and garnish with a cherry.",
      "caloriePreference": "Medium",
      "Kcal": 160,
      "flavorProfile": "Sour",
      "Location": "\/assets\/alcoholImages\/brandy\/brandy1.png"
     },
     {
      "alcoholPreferences": "Brandy",
      "Name": "brandy2",
      "Cocktail Name": "Amaretto Shake",
      "Description": "A rich, dessert-style cocktail combining brandy and amaretto with a creamy finish.",
      "Ingredients": "1 oz brandy\n1 oz amaretto\n1 oz heavy cream\nChocolate shavings (for garnish)",
      "Recipe": "1. Shake brandy, amaretto, and cream with ice.\n2. Strain into a chilled glass and garnish with chocolate shavings.",
      "caloriePreference": "Indulgent",
      "Kcal": 260,
      "flavorProfile": "Sweet, Nutty",
      "Location": "\/assets\/alcoholImages\/brandy\/brandy2.png"
     },
     {
      "alcoholPreferences": "Brandy",
      "Name": "brandy3",
      "Cocktail Name": "Brandy Sour",
      "Description": "A balanced, tangy cocktail with brandy and fresh lemon for a refreshing sour taste.",
      "Ingredients": "1 1\/2 oz brandy\n1 oz fresh lemon juice\n1\/2 oz simple syrup\nLemon twist (for garnish)",
      "Recipe": "1. Shake brandy, lemon juice, and simple syrup with ice.\n2. Strain into an ice-filled glass and garnish with a lemon twist.",
      "caloriePreference": "Low",
      "Kcal": 140,
      "flavorProfile": "Sour",
      "Location": "\/assets\/alcoholImages\/brandy\/brandy3.png"
     },
     {
      "alcoholPreferences": "Brandy",
      "Name": "brandy4",
      "Cocktail Name": "Port Wine Cocktail",
      "Description": "A smooth, slightly sweet brandy cocktail with rich port wine undertones.",
      "Ingredients": "1 oz brandy\n1 oz port wine\n1\/2 oz simple syrup\nDash of bitters\nOrange twist (for garnish)",
      "Recipe": "1. Stir brandy, port wine, simple syrup, and bitters with ice.\n2. Strain into a chilled glass and garnish with an orange twist.",
      "caloriePreference": "Medium",
      "Kcal": 170,
      "flavorProfile": "Sweet, Herbal",
      "Location": "\/assets\/alcoholImages\/brandy\/brandy4.png"
     },
     {
      "alcoholPreferences": "Brandy",
      "Name": "brandy5",
      "Cocktail Name": "Pink Lemonade Cocktail",
      "Description": "A refreshing cocktail with a pink hue, blending brandy with tart lemonade flavors.",
      "Ingredients": "1 1\/2 oz brandy\n1 oz cranberry juice\n1\/2 oz fresh lemon juice\n1\/2 oz simple syrup\nLemon wedge (for garnish)",
      "Recipe": "1. Shake brandy, cranberry juice, lemon juice, and simple syrup with ice.\n2. Strain into a chilled glass and garnish with a lemon wedge.",
      "caloriePreference": "Medium",
      "Kcal": 150,
      "flavorProfile": "Fruity, Sour",
      "Location": "\/assets\/alcoholImages\/brandy\/brandy5.png"
     },
     {
      "alcoholPreferences": "Brandy",
      "Name": "brandy6",
      "Cocktail Name": "Brandy Cobbler",
      "Description": "A fruity, refreshing drink featuring brandy, berries, and citrus.",
      "Ingredients": "2 oz brandy\n1\/2 oz simple syrup\nFresh berries (such as raspberries, blackberries, and strawberries)\nOrange slice (for garnish)",
      "Recipe": "1. In a glass, muddle the berries with simple syrup.\n2. Add brandy and fill with crushed ice. Stir gently and garnish with an orange slice.",
      "caloriePreference": "Medium",
      "Kcal": 180,
      "flavorProfile": "Fruity, Sweet",
      "Location": "\/assets\/alcoholImages\/brandy\/brandy6.png"
     },
     {
      "alcoholPreferences": "Brandy",
      "Name": "brandy7",
      "Cocktail Name": "Victor",
      "Description": "A rich, herbal brandy cocktail with vermouth and bitters, offering a sophisticated taste.",
      "Ingredients": "1 1\/2 oz brandy\n1 oz sweet vermouth\nDash of orange bitters\nOrange twist (for garnish)",
      "Recipe": "1. Stir brandy, sweet vermouth, and bitters with ice.\n2. Strain into a chilled glass and garnish with an orange twist.",
      "caloriePreference": "Medium",
      "Kcal": 150,
      "flavorProfile": "Herbal, Bitter",
      "Location": "\/assets\/alcoholImages\/brandy\/brandy7.png"
     },
     {
      "alcoholPreferences": "Sake",
      "Name": "sake1",
      "Cocktail Name": "Sake Mojito",
      "Description": "A refreshing twist on the classic mojito, blending sake with mint and lime.",
      "Ingredients": "2 oz sake\n1\/2 oz fresh lime juice\n1\/2 oz simple syrup\nFresh mint leaves\nClub soda (to top)\nMint sprig and lime wheel (for garnish)",
      "Recipe": "1. Muddle mint leaves with lime juice and simple syrup in a glass.\n2. Add sake and ice, then top with club soda.\n3. Garnish with a mint sprig and lime wheel.",
      "caloriePreference": "Low",
      "Kcal": 120,
      "flavorProfile": "Herbal, Sour",
      "Location": "\/assets\/alcoholImages\/sake\/sake1.png"
     },
     {
      "alcoholPreferences": "Sake",
      "Name": "sake2",
      "Cocktail Name": "Pink Sakura",
      "Description": "A delicate, floral cocktail inspired by cherry blossoms, with a light pink hue.",
      "Ingredients": "2 oz sake\n1 oz cherry blossom syrup (or grenadine)\n1\/2 oz fresh lemon juice\nCherry blossom (for garnish, if available)",
      "Recipe": "1. Shake sake, cherry blossom syrup, and lemon juice with ice.\n2. Strain into a chilled glass and garnish with a cherry blossom if available.",
      "caloriePreference": "Low",
      "Kcal": 140,
      "flavorProfile": "Floral, Sweet",
      "Location": "\/assets\/alcoholImages\/sake\/sake2.png"
     },
     {
      "alcoholPreferences": "Sake",
      "Name": "sake3",
      "Cocktail Name": "Sake Grapefruit Cocktail",
      "Description": " A simple, tart cocktail with a balance of grapefruit and sake.",
      "Ingredients": "2 oz sake\n2 oz fresh grapefruit juice\n1\/2 oz simple syrup\nGrapefruit slice (for garnish)",
      "Recipe": "1. Shake sake, grapefruit juice, and simple syrup with ice.\n2. Strain into a glass with fresh ice and garnish with a grapefruit slice.",
      "caloriePreference": "Low",
      "Kcal": 110,
      "flavorProfile": "Sour",
      "Location": "\/assets\/alcoholImages\/sake\/sake3.png"
     },
     {
      "alcoholPreferences": "Sake",
      "Name": "sake4",
      "Cocktail Name": "Sake Yuzu Fizz",
      "Description": "A visually stunning, light cocktail with a blue tint, thanks to butterfly pea flower water, paired with the tart flavor of yuzu.",
      "Ingredients": "2 oz sake\n1 oz yuzu juice\n1\/2 oz honey syrup (honey mixed with warm water)\n1 oz butterfly pea flower water\nClub soda (to top)\nYuzu slice or lemon twist (for garnish)",
      "Recipe": "In a glass with ice, combine sake, yuzu juice, and honey syrup.\nAdd butterfly pea flower water, then top with club soda to create a gradient effect.\nGarnish with a yuzu slice or lemon twist.",
      "caloriePreference": "Low",
      "Kcal": 130,
      "flavorProfile": "Sour, Sweet",
      "Location": "\/assets\/alcoholImages\/sake\/sake4.png"
     },
     {
      "alcoholPreferences": "Sake",
      "Name": "sake5",
      "Cocktail Name": "Thai Basil Sake Cocktail",
      "Description": "An herbaceous cocktail featuring sake and fresh Thai basil for a unique flavor profile.",
      "Ingredients": "2 oz sake\n1\/2 oz fresh lime juice\n1\/2 oz simple syrup\nFresh Thai basil leaves\nThai basil sprig (for garnish)",
      "Recipe": "1. Muddle Thai basil leaves with lime juice and simple syrup in a glass.\n2. Add sake and ice, stirring gently.\n3. Garnish with a Thai basil sprig.",
      "caloriePreference": "Low",
      "Kcal": 120,
      "flavorProfile": "Herbal, Sour",
      "Location": "\/assets\/alcoholImages\/sake\/sake5.png"
     },
     {
      "alcoholPreferences": "Sake",
      "Name": "sake6",
      "Cocktail Name": "Japanese mule",
      "Description": "A sake-based twist on the Moscow Mule with ginger and lime flavors.",
      "Ingredients": "2 oz sake\n1 oz ginger beer\n1\/2 oz fresh lime juice\nLime wheel and mint sprig (for garnish)",
      "Recipe": "1. In a glass filled with ice, combine sake and lime juice.\n2. Top with ginger beer and garnish with a lime wheel and mint sprig.",
      "caloriePreference": "Low",
      "Kcal": 140,
      "flavorProfile": "Spicy, Sour",
      "Location": "\/assets\/alcoholImages\/sake\/sake6.png"
     },
     {
      "alcoholPreferences": "Sake",
      "Name": "sake7",
      "Cocktail Name": "Ginger Delight",
      "Description": "A spicy, warming cocktail with sake and fresh ginger.",
      "Ingredients": "2 oz sake\n1 oz ginger syrup (or muddled fresh ginger with simple syrup)\n1\/2 oz fresh lemon juice\nLemon twist (for garnish)",
      "Recipe": "1. Shake sake, ginger syrup, and lemon juice with ice.\n2. Strain into a chilled glass and garnish with a lemon twist.",
      "caloriePreference": "Low",
      "Kcal": 130,
      "flavorProfile": "Spicy, Sour",
      "Location": "\/assets\/alcoholImages\/sake\/sake7.png"
     },
     {
      "alcoholPreferences": "Soju",
      "Name": "soju1",
      "Cocktail Name": "Yakult Soju",
      "Description": " A creamy, refreshing cocktail combining the tangy taste of Yakult with soju.",
      "Ingredients": "2 oz soju\n1 bottle of Yakult (2.7 oz)\n1\/2 oz lemon juice\nIce",
      "Recipe": "1. In a glass with ice, combine soju, Yakult, and lemon juice.\n2. Stir gently to mix.",
      "caloriePreference": "Low",
      "Kcal": 110,
      "flavorProfile": "Sweet, Sour",
      "Location": "\/assets\/alcoholImages\/soju\/soju1.png"
     },
     {
      "alcoholPreferences": "Soju",
      "Name": "soju2",
      "Cocktail Name": "Strawberry Basil Soju",
      "Description": "A fruity, herbaceous drink with fresh strawberries and basil mixed with soju.",
      "Ingredients": "2 oz soju\n1 oz fresh strawberry puree\nFresh basil leaves\n1\/2 oz simple syrup\nIce",
      "Recipe": "1. Muddle basil with simple syrup in a glass.\n2. Add soju, strawberry puree, and ice, stirring well.",
      "caloriePreference": "Low",
      "Kcal": 120,
      "flavorProfile": "Fruity, Herbal",
      "Location": "\/assets\/alcoholImages\/soju\/soju2.png"
     },
     {
      "alcoholPreferences": "Soju",
      "Name": "soju3",
      "Cocktail Name": "Melona Soju",
      "Description": "A creamy, melon-flavored soju cocktail using popular Korean melon ice cream.",
      "Ingredients": "2 oz soju\n1 Melona ice cream bar (honeydew flavor)\n1\/2 oz milk or soda water (optional, for a lighter taste)",
      "Recipe": "1. Place the Melona ice cream bar in a glass and pour soju over it.\n2. Optionally add milk or soda water for a lighter consistency. Stir lightly.",
      "caloriePreference": "Medium",
      "Kcal": 180,
      "flavorProfile": "Sweet, Fruity",
      "Location": "\/assets\/alcoholImages\/soju\/soju3.png"
     },
     {
      "alcoholPreferences": "Soju",
      "Name": "soju4",
      "Cocktail Name": "Apple Soju Fizz",
      "Description": "A crisp, refreshing drink with apple juice, soju, and a fizzy finish.",
      "Ingredients": "2 oz soju\n2 oz apple juice\nClub soda (to top)\nApple slice (for garnish)",
      "Recipe": "1. Combine soju and apple juice in a glass with ice.\n2. Top with club soda and garnish with an apple slice.",
      "caloriePreference": "Low",
      "Kcal": 110,
      "flavorProfile": "Sweet, Fruity",
      "Location": "\/assets\/alcoholImages\/soju\/soju4.png"
     },
     {
      "alcoholPreferences": "Soju",
      "Name": "soju5",
      "Cocktail Name": "Lemon Drop Soju",
      "Description": "A bright, citrusy twist on the classic lemon drop, using soju for a lighter taste.",
      "Ingredients": "2 oz soju\n1 oz fresh lemon juice\n1\/2 oz simple syrup\nLemon slice (for garnish)",
      "Recipe": "1. Shake soju, lemon juice, and simple syrup with ice.\n2. Strain into a glass and garnish with a lemon slice.",
      "caloriePreference": "Low",
      "Kcal": 100,
      "flavorProfile": "Sour",
      "Location": "\/assets\/alcoholImages\/soju\/soju5.png"
     },
     {
      "alcoholPreferences": "Soju",
      "Name": "soju6",
      "Cocktail Name": "Lychee Soju",
      "Description": "A light, floral cocktail with lychee flavors and a hint of sweetness.",
      "Ingredients": "2 oz soju\n1 oz lychee syrup or juice\n1\/2 oz simple syrup\nLychee fruit (for garnish)",
      "Recipe": "1. Combine soju, lychee syrup, and simple syrup in a glass with ice.\n2. Stir well and garnish with a lychee fruit.",
      "caloriePreference": "Low",
      "Kcal": 120,
      "flavorProfile": "Floral, Sweet",
      "Location": "\/assets\/alcoholImages\/soju\/soju6.png"
     },
     {
      "alcoholPreferences": "Soju",
      "Name": "soju7",
      "Cocktail Name": "Soju Sour Cocktail",
      "Description": "A tangy cocktail with a foamy texture, offering a twist on the classic sour.",
      "Ingredients": "2 oz soju\n1 oz fresh lemon juice\n1\/2 oz simple syrup\nEgg white (optional, for foam)\nLemon twist (for garnish)",
      "Recipe": "1. Dry shake (without ice) soju, lemon juice, simple syrup, and egg white if using, to create foam.\n2. Add ice and shake again, then strain into a glass. Garnish with a lemon twist.",
      "caloriePreference": "Low",
      "Kcal": 110,
      "flavorProfile": "Sour",
      "Location": "\/assets\/alcoholImages\/soju\/soju7.png"
     },
     {
      "alcoholPreferences": "Non-alcoholic",
      "Name": "nac1",
      "Cocktail Name": "Watermelon Fizz",
      "Description": "A refreshing, fruity mocktail with juicy watermelon and a fizzy twist.",
      "Ingredients": "4 oz fresh watermelon juice\n1\/2 oz fresh lime juice\nClub soda (to top)\nFresh mint leaves (for garnish)",
      "Recipe": "1. Combine watermelon and lime juice in a glass with ice.\n2. Top with club soda and garnish with mint leaves.",
      "caloriePreference": "Low",
      "Kcal": 60,
      "flavorProfile": "Fruity, Sour",
      "Location": "\/assets\/alcoholImages\/non-alcoholic\/nac1.png"
     },
     {
      "alcoholPreferences": "Non-alcoholic",
      "Name": "nac2",
      "Cocktail Name": "Summer Berry Delight",
      "Description": "A vibrant berry mocktail with mixed berries and a hint of mint for a summery vibe.",
      "Ingredients": "2 oz mixed berry puree (strawberries, blueberries, raspberries)\n1\/2 oz fresh lemon juice\n1\/2 oz simple syrup\nClub soda (to top)\nMint sprig (for garnish)",
      "Recipe": "1. Combine berry puree, lemon juice, and simple syrup in a glass with ice.\n2. Top with club soda and garnish with a mint sprig.",
      "caloriePreference": "Low",
      "Kcal": 80,
      "flavorProfile": "Fruity, Sweet",
      "Location": "\/assets\/alcoholImages\/non-alcoholic\/nac2.png"
     },
     {
      "alcoholPreferences": "Non-alcoholic",
      "Name": "nac3",
      "Cocktail Name": "Honey Yuzu Drop",
      "Description": "A citrusy, honey-sweetened mocktail featuring the exotic flavor of yuzu.",
      "Ingredients": "2 oz yuzu juice\n1\/2 oz honey syrup (honey mixed with warm water)\nClub soda (to top)\nLemon twist (for garnish)",
      "Recipe": "1. Shake yuzu juice and honey syrup with ice.\n2. Strain into a glass and top with club soda. Garnish with a lemon twist.",
      "caloriePreference": "Low",
      "Kcal": 70,
      "flavorProfile": "Sour, Sweet",
      "Location": "\/assets\/alcoholImages\/non-alcoholic\/nac3.png"
     },
     {
      "alcoholPreferences": "Non-alcoholic",
      "Name": "nac4",
      "Cocktail Name": "Hibiscus Sour",
      "Description": "A beautifully tart and floral mocktail with hibiscus and citrus notes.",
      "Ingredients": "2 oz hibiscus tea (cooled)\n1 oz fresh lime juice\n1\/2 oz simple syrup\nLime wheel (for garnish)",
      "Recipe": "1. Shake hibiscus tea, lime juice, and simple syrup with ice.\n2. Strain into a glass and garnish with a lime wheel.",
      "caloriePreference": "Low",
      "Kcal": 50,
      "flavorProfile": "Floral, Sour",
      "Location": "\/assets\/alcoholImages\/non-alcoholic\/nac4.png"
     },
     {
      "alcoholPreferences": "Non-alcoholic",
      "Name": "nac5",
      "Cocktail Name": "Lorenzo Sour",
      "Description": "A bold mocktail with a tangy, refreshing citrus and herbal flavor.",
      "Ingredients": "2 oz fresh lemon juice\n1 oz fresh orange juice\n1\/2 oz simple syrup\nBasil leaves (for garnish)",
      "Recipe": "Shake lemon juice, orange juice, and simple syrup with ice.\nStrain into a glass and garnish with fresh basil leaves.",
      "caloriePreference": "Low",
      "Kcal": 60,
      "flavorProfile": "Sour, Herbal",
      "Location": "\/assets\/alcoholImages\/non-alcoholic\/nac5.png"
     },
     {
      "alcoholPreferences": "Non-alcoholic",
      "Name": "nac6",
      "Cocktail Name": "Mojito Mocktail",
      "Description": "A classic mocktail with mint, lime, and a touch of sweetness, just like a mojito but without the alcohol.",
      "Ingredients": "1\/2 oz fresh lime juice\n1\/2 oz simple syrup\nFresh mint leaves\nClub soda (to top)\nMint sprig and lime wheel (for garnish)",
      "Recipe": "1. Muddle mint leaves with lime juice and simple syrup in a glass.\n2. Add ice, top with club soda, and garnish with mint and lime.",
      "caloriePreference": "Low",
      "Kcal": 40,
      "flavorProfile": "Herbal, Sour",
      "Location": "\/assets\/alcoholImages\/non-alcoholic\/nac6.png"
     },
     {
      "alcoholPreferences": "Non-alcoholic",
      "Name": "nac7",
      "Cocktail Name": "Cherry Crush",
      "Description": "A sweet and fruity mocktail featuring cherry and citrus for a vibrant flavor.",
      "Ingredients": "2 oz cherry juice\n1 oz fresh orange juice\n1\/2 oz simple syrup\nOrange slice (for garnish)",
      "Recipe": "1. Combine cherry juice, orange juice, and simple syrup in a glass with ice.\n2. Stir well and garnish with an orange slice.",
      "caloriePreference": "Low",
      "Kcal": 70,
      "flavorProfile": "Fruity, Sweet",
      "Location": "\/assets\/alcoholImages\/non-alcoholic\/nac7.png"
     },
     {
      "alcoholPreferences": "Non-alcoholic",
      "Name": "nac8",
      "Cocktail Name": "Smoky Jalapeño Lemonade",
      "Description": "A smoky and spicy lemonade mocktail, perfect for those who enjoy a bit of heat with a tangy twist.",
      "Ingredients": "1 charred jalapeño (cut in half, seeds removed for less heat if preferred)\n2 oz fresh lemon juice\n1\/2 oz agave syrup (or simple syrup)\n3 oz smoked tea (such as lapsang souchong, cooled) or a few drops of liquid smoke for extra intensity\nClub soda (to top)\nLemon wheel and jalapeño slice (for garnish)",
      "Recipe": "1. Char the jalapeño halves on a stovetop or grill for a smoky flavor, then muddle it with lemon juice and agave syrup in a shaker.\n2. Add the smoked tea or a few drops of liquid smoke, then shake with ice.\n3. Strain into a glass filled with fresh ice and top with club soda.\n4. Garnish with a lemon wheel and a slice of fresh or charred jalapeño.",
      "caloriePreference": "Low",
      "Kcal": 50,
      "flavorProfile": "Smoky, Spicy",
      "Location": "\/assets\/alcoholImages\/non-alcoholic\/nac8.png"
     },
     {
      "alcoholPreferences": "Non-alcoholic",
      "Name": "nac9",
      "Cocktail Name": "Almond Date Delight",
      "Description": "A creamy, nutty mocktail with rich almond and sweet date flavors, perfect for dessert lovers.",
      "Ingredients": "1 oz almond milk\n1 oz coconut milk\n1 tbsp date syrup (or a few pitted dates, blended)\n1\/2 tsp almond extract\nCrushed ice\nToasted almond slivers (for garnish)",
      "Recipe": "1. Blend almond milk, coconut milk, date syrup (or dates), and almond extract with crushed ice until smooth.\n2. Pour into a glass and garnish with toasted almond slivers.",
      "caloriePreference": "Low",
      "Kcal": 100,
      "flavorProfile": "Nutty, Sweet",
      "Location": "\/assets\/alcoholImages\/non-alcoholic\/nac9.png"
     },
     {
      "alcoholPreferences": "Non-alcoholic",
      "Name": "nac10",
      "Cocktail Name": "Charred Grapefruit Mocktail",
      "Description": "A bold, bitter mocktail with a smoky edge, thanks to charred grapefruit and a hint of smoked salt.",
      "Ingredients": "2 oz fresh grapefruit juice (from a charred grapefruit for extra smoky flavor)\n1\/2 oz honey or agave syrup\nSmoked salt (pinch)\nClub soda (to top)\nCharred grapefruit wedge (for garnish)",
      "Recipe": "1. Char a grapefruit half on a grill or stovetop until it has a smoky, caramelized aroma.\n2. Squeeze out 2 oz of juice and combine with honey or agave syrup in a glass.\n3. Add a pinch of smoked salt and ice, then top with club soda.\nGarnish with a charred grapefruit wedge.",
      "caloriePreference": "Low",
      "Kcal": 70,
      "flavorProfile": "Bitter, Smoky",
      "Location": "\/assets\/alcoholImages\/non-alcoholic\/nac10.png"
     },
     {
      "alcoholPreferences": "Non-alcoholic",
      "Name": "nac11",
      "Cocktail Name": "Cashew Cinnamon Mule",
      "Description": "A unique twist on a classic mule with creamy cashew milk and a spicy kick from ginger and cinnamon.",
      "Ingredients": "2 oz cashew milk\n1 oz ginger syrup (or fresh ginger juice for more spice)\n1\/2 tsp cinnamon\nGinger beer (to top)\nCinnamon stick and crystallized ginger (for garnish)",
      "Recipe": "1. Combine cashew milk, ginger syrup, and cinnamon in a shaker with ice and shake well.\n2. Pour into a glass with ice and top with ginger beer.\n3. Garnish with a cinnamon stick and a piece of crystallized ginger.",
      "caloriePreference": "Low",
      "Kcal": 90,
      "flavorProfile": "Nutty, Spicy",
      "Location": "\/assets\/alcoholImages\/non-alcoholic\/nac11.png"
     },
     {
      "alcoholPreferences": "Non-alcoholic",
      "Name": "nac12",
      "Cocktail Name": "Rose Chili Lassi",
      "Description": "A luxurious floral mocktail with the creamy richness of yogurt, the delicate aroma of rose, and a spicy chili kick.",
      "Ingredients": "3 oz plain Greek yogurt (or coconut yogurt for a dairy-free version)\n1 oz rose water\n1 tbsp honey or sugar (adjust for sweetness)\n1\/4 tsp chili powder (or cayenne, for extra heat)\n1\/2 oz fresh lime juice\n2 oz water or milk (to thin)\nIce cubes (optional)\nRose petals and a pinch of chili powder (for garnish)",
      "Recipe": "1. Blend yogurt, rose water, honey, chili powder, lime juice, and water\/milk until smooth. Add ice cubes for a chilled version.\n2. Pour into a glass and garnish with rose petals and a light sprinkle of chili powder.",
      "caloriePreference": "Indulgent",
      "Kcal": 200,
      "flavorProfile": "Floral, Spicy",
      "Location": "\/assets\/alcoholImages\/non-alcoholic\/nac12.png"
     },
     {
      "alcoholPreferences": "Non-alcoholic",
      "Name": "nac13",
      "Cocktail Name": "Lavender Grapefruit Tonic",
      "Description": "A refreshing mocktail that pairs the bitterness of grapefruit with the soft floral notes of lavender.",
      "Ingredients": "2 oz fresh grapefruit juice\n1\/2 oz lavender syrup (or a few drops of food-grade lavender essence)\n1 oz tonic water (or club soda for less bitterness)\nGrapefruit twist and dried lavender sprig (for garnish)",
      "Recipe": "1. Mix grapefruit juice and lavender syrup in a glass with ice.\n2. Top with tonic water and gently stir.\n3. Garnish with a grapefruit twist and a sprig of dried lavender.",
      "caloriePreference": "Low",
      "Kcal": 50,
      "flavorProfile": "Floral, Bitter",
      "Location": "\/assets\/alcoholImages\/non-alcoholic\/nac13.png"
     },
     {
      "alcoholPreferences": "Vodka",
      "Name": "vodka1",
      "Cocktail Name": "Kamikaze",
      "Description": "A crisp and tangy vodka cocktail with fresh lime, perfect for a quick, zesty drink.",
      "Ingredients": "1 oz vodka\n1 oz triple sec\n1 oz fresh lime juice",
      "Recipe": "1. Shake vodka, triple sec, and lime juice with ice.\n2. Strain into a chilled glass.",
      "caloriePreference": "Medium",
      "Kcal": 130,
      "flavorProfile": "Sour",
      "Location": "\/assets\/alcoholImages\/vodka\/vodka1.png"
     },
     {
      "alcoholPreferences": "Vodka",
      "Name": "vodka2",
      "Cocktail Name": "Pornstar Martini",
      "Description": "A sweet, exotic cocktail with passion fruit, often served with a side of sparkling wine.",
      "Ingredients": "1.5 oz vodka\n1 oz passion fruit juice or puree\n1\/2 oz vanilla syrup\nProsecco (optional, to top)",
      "Recipe": "1. Shake vodka, passion fruit juice, and vanilla syrup with ice.\n2. Strain into a martini glass, and top with Prosecco if desired.",
      "caloriePreference": "Medium",
      "Kcal": 160,
      "flavorProfile": "Fruity, Sweet",
      "Location": "\/assets\/alcoholImages\/vodka\/vodka2.png"
     },
     {
      "alcoholPreferences": "Vodka",
      "Name": "vodka3",
      "Cocktail Name": "Cosmopolitan",
      "Description": "A timeless cocktail with vodka, cranberry, and citrus for a refreshing balance.",
      "Ingredients": "1.5 oz vodka\n1 oz cranberry juice\n1\/2 oz triple sec\n1\/2 oz fresh lime juice",
      "Recipe": "1. Shake all ingredients with ice and strain into a martini glass.",
      "caloriePreference": "Medium",
      "Kcal": 140,
      "flavorProfile": "Fruity, Sour",
      "Location": "\/assets\/alcoholImages\/vodka\/vodka3.png"
     },
     {
      "alcoholPreferences": "Vodka",
      "Name": "vodka4",
      "Cocktail Name": "Vodka Sunrise",
      "Description": "A colorful, fruity drink featuring vodka and orange juice with a hint of grenadine.",
      "Ingredients": "1.5 oz vodka\n3 oz orange juice\n1\/2 oz grenadine",
      "Recipe": "1. Pour vodka and orange juice into a glass with ice.\n2. Add grenadine for a “sunrise” effect.",
      "caloriePreference": "Medium",
      "Kcal": 150,
      "flavorProfile": "Fruity, Sweet",
      "Location": "\/assets\/alcoholImages\/vodka\/vodka4.png"
     },
     {
      "alcoholPreferences": "Vodka",
      "Name": "vodka5",
      "Cocktail Name": "Vanilla Hazelnut White Russian",
      "Description": "A rich, creamy cocktail with flavors of hazelnut and vanilla, perfect for dessert.",
      "Ingredients": "1 oz vodka\n1 oz coffee liqueur\n1 oz hazelnut milk (or cream)\n1\/2 oz vanilla syrup",
      "Recipe": "1. Pour vodka, coffee liqueur, and vanilla syrup over ice.\n2. Add hazelnut milk and stir gently.",
      "caloriePreference": "Indulgent",
      "Kcal": 250,
      "flavorProfile": "Nutty, Sweet",
      "Location": "\/assets\/alcoholImages\/vodka\/vodka5.png"
     },
     {
      "alcoholPreferences": "Vodka",
      "Name": "vodka6",
      "Cocktail Name": "Ginger Chili Mule",
      "Description": "A zesty, spicy mule with a kick of ginger and chili, balanced with sweetness.",
      "Ingredients": "1.5 oz vodka\n3 oz ginger beer\n1\/2 oz lime juice\nA pinch of chili powder (or muddle fresh chili)",
      "Recipe": "Combine vodka, lime juice, and chili powder in a glass with ice.\nTop with ginger beer and stir.",
      "caloriePreference": "Medium",
      "Kcal": 140,
      "flavorProfile": "Spicy, Sour",
      "Location": "\/assets\/alcoholImages\/vodka\/vodka6.png"
     },
     {
      "alcoholPreferences": "Vodka",
      "Name": "vodka7",
      "Cocktail Name": "Lavender Smoke Martini",
      "Description": "A sophisticated blend of smoky and floral flavors, thanks to smoked tea and lavender syrup.",
      "Ingredients": "1.5 oz vodka\n1\/2 oz lavender syrup\n1\/2 oz chilled lapsang souchong tea (for smokiness)",
      "Recipe": "1. Shake vodka, lavender syrup, and tea with ice.\n2. Strain into a chilled martini glass and garnish with a lavender sprig.",
      "caloriePreference": "Medium",
      "Kcal": 120,
      "flavorProfile": "Smoky, Floral",
      "Location": "\/assets\/alcoholImages\/vodka\/vodka7.png"
     },
     {
      "alcoholPreferences": "Vodka",
      "Name": "vodka8",
      "Cocktail Name": "Toasted Almond Vodka Fizz",
      "Description": "A light and refreshing take on a nutty vodka fizz, featuring almond and a hint of vanilla without the extra calories.",
      "Ingredients": "1.5 oz vodka\n1 oz unsweetened almond milk\n1\/4 oz vanilla extract (instead of syrup, for flavor without added sugar)\nClub soda (to top)\nOptional: A few drops of stevia or monk fruit sweetener, to taste",
      "Recipe": "1. Shake vodka, almond milk, and vanilla extract with ice.\n2. Strain into a glass and top with club soda.\n3. Add a few drops of stevia or monk fruit sweetener if extra sweetness is desired.",
      "caloriePreference": "Low",
      "Kcal": 90,
      "flavorProfile": "Nutty, Sweet",
      "Location": "\/assets\/alcoholImages\/vodka\/vodka8.png"
     },
     {
      "alcoholPreferences": "Wine",
      "Name": "wine1",
      "Cocktail Name": "Rose Wine Cocktail",
      "Description": "A crisp and refreshing cocktail with the floral notes of rose wine and a touch of sweetness.",
      "Ingredients": "3 oz rosé wine\n1 oz elderflower liqueur (or syrup for a non-alcoholic version)\n1\/2 oz lemon juice\nSparkling water (to top)",
      "Recipe": "1. Mix rosé wine, elderflower liqueur, and lemon juice in a glass with ice.\n2. Top with sparkling water.\n3. Stir gently and garnish with a lemon twist.",
      "caloriePreference": "Medium",
      "Kcal": 130,
      "flavorProfile": "Floral, Sweet",
      "Location": "\/assets\/alcoholImages\/wine\/wine1.png"
     },
     {
      "alcoholPreferences": "Wine",
      "Name": "wine2",
      "Cocktail Name": "White Wine Sangria",
      "Description": "A fruity and vibrant wine cocktail with a blend of citrus fruits and a refreshing white wine base.",
      "Ingredients": "3 oz white wine (dry)\n1 oz brandy (optional)\n1\/2 oz orange liqueur\nSliced citrus fruits (oranges, lemons)\n1-2 tsp honey (optional)\nSparkling water (to top)",
      "Recipe": "1. In a pitcher, combine white wine, brandy (if using), orange liqueur, and honey.\n2. Add sliced citrus fruits and let it chill in the fridge for at least 2 hours.\n3. Before serving, top with sparkling water and serve over ice.",
      "caloriePreference": "Medium",
      "Kcal": 150,
      "flavorProfile": "Fruity, Herbal",
      "Location": "\/assets\/alcoholImages\/wine\/wine2.png"
     },
     {
      "alcoholPreferences": "Wine",
      "Name": "wine3",
      "Cocktail Name": "Grapefruit Punch",
      "Description": "A tangy, citrusy wine punch with grapefruit and a kick of sweetness, perfect for a refreshing summer drink.",
      "Ingredients": "3 oz white wine (dry or semi-dry)\n1 oz fresh grapefruit juice\n1\/2 oz simple syrup or agave syrup\nA dash of bitters\nGrapefruit slice (for garnish)",
      "Recipe": "1. Combine white wine, grapefruit juice, simple syrup, and bitters in a shaker with ice.\n2. Shake and strain into a glass.\n3. Garnish with a grapefruit slice.",
      "caloriePreference": "Medium",
      "Kcal": 120,
      "flavorProfile": "Sour, Bitter",
      "Location": "\/assets\/alcoholImages\/wine\/wine3.png"
     },
     {
      "alcoholPreferences": "Wine",
      "Name": "wine4",
      "Cocktail Name": "Spanish Wine Cocktail",
      "Description": "A classic Spanish cocktail with the warmth of red wine and a hint of citrus.",
      "Ingredients": "3 oz red wine (Spanish, such as Tempranillo)\n1 oz orange juice\n1\/2 oz brandy\n1\/2 oz simple syrup (optional)\nOrange slice (for garnish)",
      "Recipe": "1. In a glass, combine red wine, orange juice, brandy, and simple syrup.\n2. Stir gently and garnish with an orange slice.",
      "caloriePreference": "Medium",
      "Kcal": 180,
      "flavorProfile": "Fruity, Bitter",
      "Location": "\/assets\/alcoholImages\/wine\/wine4.png"
     },
     {
      "alcoholPreferences": "Wine",
      "Name": "wine5",
      "Cocktail Name": "Cherry Fizz",
      "Description": "A fizzy, tart cocktail with the bright flavor of cherries and a refreshing wine base.",
      "Ingredients": "3 oz white wine (dry)\n1 oz cherry juice (or muddled fresh cherries)\n1\/2 oz lemon juice\nClub soda (to top)\nMaraschino cherry (for garnish)",
      "Recipe": "1. Muddle fresh cherries (or use cherry juice), then add white wine, lemon juice, and ice.\n2. Shake well, strain into a glass, and top with club soda.\n3. Garnish with a maraschino cherry.",
      "caloriePreference": "Medium",
      "Kcal": 140,
      "flavorProfile": "Fruity, Sweet",
      "Location": "\/assets\/alcoholImages\/wine\/wine5.png"
     },
     {
      "alcoholPreferences": "Wine",
      "Name": "wine6",
      "Cocktail Name": "White Wine Grapefruit Mojito",
      "Description": "A twist on the classic mojito, combining white wine, mint, and the tang of grapefruit.",
      "Ingredients": "3 oz white wine (dry)\n1 oz fresh grapefruit juice\n1\/2 oz simple syrup\nFresh mint leaves\nClub soda (to top)\nGrapefruit wedge (for garnish)",
      "Recipe": "1. Muddle fresh mint leaves and simple syrup in a glass.\n2. Add white wine, grapefruit juice, and ice. Stir well.\n3. Top with club soda and garnish with a grapefruit wedge and mint sprig.",
      "caloriePreference": "Medium",
      "Kcal": 110,
      "flavorProfile": "Fruity, Herbal",
      "Location": "\/assets\/alcoholImages\/wine\/wine6.png"
     },
     {
      "alcoholPreferences": "Wine",
      "Name": "wine7",
      "Cocktail Name": "Earl Grey Spritz",
      "Description": "A sophisticated and refreshing spritz with the aromatic flavor of Earl Grey tea and the effervescence of sparkling wine.",
      "Ingredients": "3 oz sparkling wine (Prosecco or Champagne)\n1 oz Earl Grey tea (cooled)\n1\/2 oz honey syrup\nLemon twist (for garnish)",
      "Recipe": "1. Combine Earl Grey tea and honey syrup in a glass with ice.\n2. Top with sparkling wine and stir gently.\n3. Garnish with a lemon twist.",
      "caloriePreference": "Medium",
      "Kcal": 130,
      "flavorProfile": "Herbal, Floral",
      "Location": "\/assets\/alcoholImages\/wine\/wine7.png"
     },
     {
      "alcoholPreferences": "Whiskey",
      "Name": "whiskey1",
      "Cocktail Name": "Cranberry Orange Whiskey Cocktail",
      "Description": "A vibrant whiskey cocktail with tart cranberry and refreshing orange, balanced by the warmth of whiskey.",
      "Ingredients": "2 oz whiskey (bourbon or rye)\n1 oz cranberry juice\n1 oz fresh orange juice\n1\/2 oz simple syrup (optional)\nOrange slice or cranberries for garnish",
      "Recipe": "1. Shake whiskey, cranberry juice, orange juice, and simple syrup (if using) with ice.\n2. Strain into a glass filled with ice.\n3. Garnish with an orange slice or cranberries.",
      "caloriePreference": "Medium",
      "Kcal": 160,
      "flavorProfile": "Fruity, Sour",
      "Location": "\/assets\/alcoholImages\/whiskey\/whiskey1.png"
     },
     {
      "alcoholPreferences": "Whiskey",
      "Name": "whiskey2",
      "Cocktail Name": "Smokey Thyme Whiskey",
      "Description": "A smoky and herbal cocktail with the rich flavor of peated whiskey and the earthy notes of thyme.",
      "Ingredients": "2 oz smoky whiskey (such as Laphroaig or another peated Scotch)\n1\/2 oz honey syrup (1:1 honey to water)\n1\/2 oz fresh lemon juice\n2-3 sprigs fresh thyme\nDash of Angostura bitters\nIce cubes\nLemon twist or thyme sprig (for garnish)",
      "Recipe": "1. Muddle the thyme sprigs in a cocktail shaker to release the herbal oils.\n2. Add whiskey, honey syrup, lemon juice, and bitters.\n3. Shake with ice and strain into an old-fashioned glass filled with ice.\n4. Garnish with a lemon twist or a sprig of thyme.",
      "caloriePreference": "Medium",
      "Kcal": 180,
      "flavorProfile": "Smoky, Herbal",
      "Location": "\/assets\/alcoholImages\/whiskey\/whiskey2.png"
     },
     {
      "alcoholPreferences": "Whiskey",
      "Name": "whiskey3",
      "Cocktail Name": "Bitter Lemon Whiskey Sour",
      "Description": "A tart twist on the classic whiskey sour, with the sharpness of bitter lemon adding depth to the citrus flavor.",
      "Ingredients": "2 oz whiskey (bourbon or rye)\n3\/4 oz fresh lemon juice\n1\/2 oz simple syrup\n1 oz bitter lemon soda\nLemon wheel or peel for garnish",
      "Recipe": "1. Shake whiskey, lemon juice, and simple syrup with ice.\n2. Strain into a glass and top with bitter lemon soda.\n3. Garnish with a lemon wheel or peel.",
      "caloriePreference": "Medium",
      "Kcal": 150,
      "flavorProfile": "Sour, Bitter",
      "Location": "\/assets\/alcoholImages\/whiskey\/whiskey3.png"
     },
     {
      "alcoholPreferences": "Whiskey",
      "Name": "whiskey4",
      "Cocktail Name": "Old Fashioned",
      "Description": "A timeless cocktail with whiskey, bitters, and a hint of sweetness, served over ice with a citrus twist.",
      "Ingredients": "2 oz whiskey (bourbon or rye)\n2 dashes Angostura bitters\n1 sugar cube\nOrange peel",
      "Recipe": "1. Muddle the sugar cube and bitters in a glass.\n2. Add whiskey and ice, then stir.\n3. Garnish with an orange peel twist.",
      "caloriePreference": "Medium",
      "Kcal": 180,
      "flavorProfile": "Bitter, Sweet",
      "Location": "\/assets\/alcoholImages\/whiskey\/whiskey4.png"
     },
     {
      "alcoholPreferences": "Whiskey",
      "Name": "whiskey5",
      "Cocktail Name": "Strawberry Samurai Japanese Whiskey",
      "Description": "A unique whiskey cocktail with the fruity sweetness of strawberry and the smooth richness of Japanese whiskey.",
      "Ingredients": "2 oz Japanese whiskey (such as Hibiki or Yamazaki)\n1 oz strawberry puree\n1\/2 oz fresh lemon juice\n1\/2 oz simple syrup\nFresh strawberry for garnish",
      "Recipe": "1. Shake whiskey, strawberry puree, lemon juice, and simple syrup with ice.\n2. Strain into a glass filled with ice.\n3. Garnish with a fresh strawberry.",
      "caloriePreference": "Medium",
      "Kcal": 160,
      "flavorProfile": "Fruity, Sweet",
      "Location": "\/assets\/alcoholImages\/whiskey\/whiskey5.png"
     },
     {
      "alcoholPreferences": "Whiskey",
      "Name": "whiskey6",
      "Cocktail Name": "Whiskey Ginger",
      "Description": "A simple and refreshing combination of whiskey and ginger ale with a citrus twist.",
      "Ingredients": "2 oz whiskey (bourbon or rye)\n4 oz ginger ale\nLemon wedge for garnish",
      "Recipe": "1. Fill a glass with ice and add whiskey.\n2. Top with ginger ale.\n3. Garnish with a lemon wedge.",
      "caloriePreference": "Medium",
      "Kcal": 140,
      "flavorProfile": "Sweet, Spicy",
      "Location": "\/assets\/alcoholImages\/whiskey\/whiskey6.png"
     },
     {
      "alcoholPreferences": "Whiskey",
      "Name": "whiskey7",
      "Cocktail Name": "Cinnabon Highball",
      "Description": "A dessert-inspired cocktail with whiskey and a warm cinnamon flavor, perfect for a cozy night.",
      "Ingredients": "2 oz whiskey (bourbon or rye)\n4 oz ginger ale\n1\/4 tsp ground cinnamon\nCinnamon stick for garnish",
      "Recipe": "1. Add whiskey and ginger ale to a glass filled with ice.\n2. Sprinkle ground cinnamon over the drink and stir.\n3. Garnish with a cinnamon stick.",
      "caloriePreference": "Medium",
      "Kcal": 160,
      "flavorProfile": "Spicy, Sweet",
      "Location": "\/assets\/alcoholImages\/whiskey\/whiskey7.png"
     },
     {
      "alcoholPreferences": "Whiskey",
      "Name": "whiskey8",
      "Cocktail Name": "Tamarind Whiskey Sour",
      "Description": "A tangy twist on the classic whiskey sour, with tamarind's tartness enhancing the citrus flavors.",
      "Ingredients": "2 oz whiskey (bourbon or rye)\n3\/4 oz fresh tamarind puree (or tamarind concentrate)\n1\/2 oz fresh lemon juice\n1\/2 oz simple syrup\nLemon wedge for garnish",
      "Recipe": "1. Shake whiskey, tamarind puree, lemon juice, and simple syrup with ice.\n2. Strain into a glass filled with ice.\n3. Garnish with a lemon wedge.",
      "caloriePreference": "Medium",
      "Kcal": 150,
      "flavorProfile": "Sour, Fruity",
      "Location": "\/assets\/alcoholImages\/whiskey\/whiskey8.png"
     }
];

window.global_cocktails = cocktails;
